name: laborator1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/v2.json
    - assets/BarberHouse.png
    - assets/Barberman.jpg
    - assets/BlackPanther.jpg
    - assets/CrazyMonkey.png
    - assets/Garage.jpg
    - assets/MenClub.png
    - assets/SVOY.png
    - assets/topgun.png
    - assets/UnclePete.png
    - assets/banner.png
